spring.application.name=precificacao3d

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/precificacao3d
spring.datasource.username=precificacao_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate