CREATE TABLE filamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    marca VARCHAR(100),
    cor VARCHAR(50),
    preco_por_kg NUMERIC(12, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_filamentos_preco_positivo
        CHECK (preco_por_kg > 0)
);