CREATE TABLE printers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    power_watts NUMERIC(10, 2) NOT NULL,
    purchase_price NUMERIC(10, 2),
    estimated_lifespan_hours NUMERIC(12, 2),
    maintenance_cost_per_hour NUMERIC(10, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);